# Use root/example as user/password credentials
version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./peppermint/db:/data/db
    environment: 
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  client:
    container_name: peppermint
    image: pepperlabs/peppermint:dev
    ports:
      - 5001:5001
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 5001 ## This is the port of the internal application there is no need to change this
      SRV_INSTANCE: "\SQLEXPRESS"
      DATABASE: "postgres1"
      DB_USERNAME: "AxisMIS"
      DB_PASSWORD: "AxisMIS"
      DB_HOST: "XPS-NINJA2"
      DATABASE_URL: "sqlserver://${DB_HOST}${SRV_INSTANCE};database=${DATABASE};username=${DB_USERNAME};password=${DB_PASSWORD};trustServerCertificate=true;"
      BASE_URL: "http://localhost:5001"