BEGIN TRY

BEGIN TRAN;

-- AlterTable
EXEC SP_RENAME N'dbo.Todos_pkey', N'PK_Todos';

-- CreateTable
CREATE TABLE [dbo].[Notes] (
    [id] INT NOT NULL IDENTITY(1,1),
    [createdAt] DATETIME NOT NULL CONSTRAINT [DF_Notes_createdAt] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME NOT NULL CONSTRAINT [DF_Notes_updatedAt] DEFAULT CURRENT_TIMESTAMP,
    [title] NVARCHAR(max) NOT NULL,
    [note] NVARCHAR(max) NOT NULL,
    [createdBy] INT NOT NULL,
    [userId] INT NOT NULL,
    CONSTRAINT [PK_Notes] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
