BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[UserFile] (
    [id] INT NOT NULL IDENTITY(1,1),
    [createdAt] DATETIME NOT NULL CONSTRAINT [DF_UserFile_createdAt] DEFAULT CURRENT_TIMESTAMP,
    [filename] NVARCHAR(max) NOT NULL,
    [path] NVARCHAR(max) NOT NULL,
    [userId] INT NOT NULL,
    [user] INT NOT NULL,
    CONSTRAINT [PK_UserFile] PRIMARY KEY CLUSTERED ([id])
);

-- CreateTable
CREATE TABLE [dbo].[TicketFile] (
    [id] INT NOT NULL IDENTITY(1,1),
    [createdAt] DATETIME NOT NULL CONSTRAINT [DF_TicketFile_createdAt] DEFAULT CURRENT_TIMESTAMP,
    [filename] NVARCHAR(1000) NOT NULL,
    [path] NVARCHAR(1000) NOT NULL,
    [ticketId] INT NOT NULL,
    [ticket] INT NOT NULL,
    CONSTRAINT [PK_TicketFile] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
